name: previous
version: '2.2svn'
base: core18
summary: Previous is a Next computer hardware emulator.
description: |
  Previous is a Next computer hardware emulator. It aims to emulate a Next Cube or a Next Station with all its peripheral.
  Previous is derived from the Hatari emulator sources that are partly based on the amiga emulator UAE. Some Previous source code files are now back in Hatari's source code for 680[34]0 MMU correctness.

  http://previous.alternative-system.com/


architectures: 
  - amd64

grade: stable
confinement: strict

icon: snap/gui/previous.png

apps:
  previous:
    command: usr/bin/previous
    plugs:
      - alsa
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - pulseaudio
      - network
      - unity7
      - wayland
      - x11

parts:

  local:
    source: snap/local
    plugin: dump
    override-prime: |
      /bin/true
    
  previous:
    plugin: autotools
    configflags: [--prefix=/snap/previous/current/usr]
    source-type: svn
    source: https://svn.code.sf.net/p/previous/code/branches/branch_softfloat
    build-packages:
      - build-essential
      - cmake
      - libsdl2-dev
      - libreadline-dev
      - libpng-dev
      - libpcap-dev
      - zlib1g-dev
    override-pull: |
      snapcraftctl pull
      patch -p1 < ${SNAPCRAFT_STAGE}/confdir.patch
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/previous
      cp ${SNAPCRAFT_STAGE}/dimension_eeprom.bin ${SNAPCRAFT_PART_INSTALL}/usr/share/previous
      cp ${SNAPCRAFT_STAGE}/previous.cfg ${SNAPCRAFT_PART_INSTALL}/etc
      mv ${SNAPCRAFT_PART_INSTALL}/snap/previous/current/usr/bin/Previous ${SNAPCRAFT_PART_INSTALL}/usr/bin/previous
      strip ${SNAPCRAFT_PART_INSTALL}/usr/bin/previous
      mv ${SNAPCRAFT_PART_INSTALL}/snap/previous/current/usr/bin/* ${SNAPCRAFT_PART_INSTALL}/usr/share/previous
      mv ${SNAPCRAFT_PART_INSTALL}/usr/lib/x86_64-linux-gnu/pulseaudio/* ${SNAPCRAFT_PART_INSTALL}/usr/lib/x86_64-linux-gnu/
      rm -r ${SNAPCRAFT_PART_INSTALL}/snap/ ${SNAPCRAFT_PART_INSTALL}/usr/lib/x86_64-linux-gnu/pulseaudio/
    stage-packages:
      - libpcap0.8
      - libpng16-16
      - libsdl2-2.0-0
    after:
      - local
